### ISSUE TITLE
Automatic locales building

### ISSUE THREAD

**Issue by nin-jin** [instrumentisto/mol-app-example#8]
I was found this non portable code in your package.json ```cp ./lang/* ./webmasters/testapp/-/``` that not needed because mam builder supports locales building from modules.

You can add files with names like ```bench.locale=ru.json``` (https://github.com/eigenmethod/mol/blob/master/bench/bench.locale%3Dru.json), that will be bundled to ```web.locale=ru.json```

**Comment by romandragan** [comment]
Nice feature
